### PR TITLE
Fix bug in Deconvolve drawK with non-rectilinear steps

### PR DESCRIPTION
**Pull request by rmjarvis**
This fixes a bug identified by @esheldon in issue #834 that I accidentally introduced in #799.

I added two new unit tests.  The one in test_metacal.py is pretty close to what Erin posted in the bug report.  The other (in test_compound.py) is a bit closer to the proximate source of the error and tests that a transform commutes with a deconvolve.  (Other than the flux scaling, which isn't expected to commute.)

### CODE REVIEW

**Comment by jmeyers314** [comment]
Looks good to me Mike.  My only comment was going to be about the junk*fits files, but I see you already addressed that.

**Comment by rmjarvis** [comment]
Yep.  I did my own code review and noticed them, so I removed them.  :)

**Comment by rmandelb** [comment]
This all looks good to me.

**Comment by rmjarvis** [comment]
@esheldon Could you please try out this branch to make sure it fixes your original error?

**Comment by esheldon** [comment]
Yes i will, probably tomorrow.

**Comment by esheldon** [comment]
This works for me.

**Comment by rmjarvis** [comment]
Great.  Thanks, Erin.

**Pull request merged**
