### PR TITLE
#637

### PR DESCRIPTION
**Pull request by rmandelb**
A quick fix for the problem David highlighted in #637.

### CODE REVIEW

**Comment by rmjarvis** [comment]
Looks good to me.  Tests pass on my systems.

**Comment by rmandelb** [comment]
This is pretty small, so are you okay with my merging it without another person to review it?

**Comment by rmjarvis** [comment]
I think you can go ahead and merge.

**Comment by rmandelb** [comment]
Thanks!

**Comment by rmandelb** [comment]
Merging #638.

**Pull request merged**
