### PR TITLE
Remove unused modules

### PR DESCRIPTION
**Pull request by AlexKurek**

### CODE REVIEW

**Comment by rmjarvis** [comment]
This breaks the unit tests.  Did you try running the tests yourself before submitting the PR?

**Comment by AlexKurek** [comment]
> This breaks the unit tests. Did you try running the tests yourself before submitting the PR?

Not really, I didnt even know it is possible to run the test by myself (offline?).
It seems I remove some actually needed module(s). Interesting that only MacOS test failed.

**Comment by rmjarvis** [comment]
Once one of them fails, the rest are canceled.  That's standard GHA behavior.  The MacOS run just happened to be the first one to get to the error.

And yes, you can run the tests yourself.  Install the code on your branch.  Then run `pytest` in the tests directory.

**Comment by AlexKurek** [comment]
I can see that it is only the test modules that fail to be imported, but I do not yet know why.

**Comment by AlexKurek** [comment]
I am not making much progress fixing this. Is it okay if I undo my changes and do it again, this time testing things locally?

**Comment by rmjarvis** [comment]
>  Is it okay if I undo my changes and do it again, this time testing things locally?
Sure.

**Pull request closed without merging**
