### PR TITLE
#683

### PR DESCRIPTION
**Pull request by jmeyers314**
These are just a few minor changes to the way chromatic profiles' `drawImage` methods setup output `Image`s.  In general, the following `kwargs` are not needed once an image is setup, and therefore it's a good idea to just remove them from `kwargs` once an image exists: `dtype`, `scale`, `wcs`, `nx`, `ny`, `bounds`.  We were doing this inconsistently before, so this PR just introduces consistency and a simple unit test to verify that previous problems are gone.

### CODE REVIEW

**Comment by rmandelb** [comment]
Looks good to me.  Tests pass on both my machines.  Need to update CHANGELOG, otherwise I'm fine with merging.

**Comment by jmeyers314** [comment]
Thanks @rmandelb .

Added to the CHANGELOG:
```
- Fixed a bug in the way Images are instantiated for certain combinations of
  ChromaticObjects and image-setup keyword arguments (#683)
```

**Comment by rmandelb** [comment]
Great, thanks.

**Comment by rmjarvis** [comment]
Finally getting around to looking at these PRs now.  

My only comment on this one is that the same list of pop commands appears 5 times within the same file.  To me this begs to be a helper function.  Maybe `_remove_setup_kwargs(kwargs)` or something along those lines.

**Comment by jmeyers314** [comment]
>To me this begs to be a helper function. Maybe _remove_setup_kwargs(kwargs) or something along those lines.

Sounds good to me.  Done.

**Comment by rmjarvis** [comment]
Good.  Looks fine to merger I think.

**Pull request merged**
