### PR TITLE
#880 Fix error in ra,dec -> x,y for SIP convergence

### PR DESCRIPTION
**Pull request by rmjarvis**
When working on WFIrst stuff, Troxel found a bug in the GSFitsWCS class where it would sometimes not converge going from ra,dec -> x,y when the WCS included a SIP component.  Basically, the target precision (1.e-8 arcsec) was too tight to always be able to meet it in double precision.  

So I adjusted the tolerance to 1.e-6 arcsec (which should still be plenty), and now it checks if the relative changes in x,y are below 1.e-15, in which case it declares it to be converged regardless of the agreement with the sky value.

I also moved this bit to C++, since it was rather slow to do the iteration in python with numpy.linalg.  Now it uses TMV, which is quite a bit quicker.

### CODE REVIEW

**Comment by rmandelb** [comment]
Tests pass on my Mac.  I'm getting some failures on my Linux cluster (and based on previous issues I went so far as to do a completely clean install of this branch starting from ```rm -rf .scon*```, but they persisted).

```
FAIL: test_sensor.test_sensor_wavelengths_and_angles
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python27/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rmandelb/git/GalSim/tests/galsim_test_helpers.py", line 542, in f2
    result = f(*args, **kwargs)
  File "/home/rmandelb/git/GalSim/tests/test_sensor.py", line 395, in test_sensor_wavelengths_and_angles
    assert r4 > r1
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Starting test_wavelengths_and_angles
Testing Wavelength and Angle sampling - i band
Flux = 3539:                sum        peak          radius
No lamb, no angles:         3503.0     435.00       0.309004
W/ lamb, no angles:         3502.0     435.00       0.308952
No lamb, w/ angles:         3503.0     429.00       0.308881
W/ lamb, w/ angles:         3503.0     408.00       0.320105
check r4 > r1 due to added wavelengths and angles
r1 = 0.309004, r4 = 0.320105, 2*sigma_r = 0.010086
Testing Wavelength and Angle sampling - i band
Flux = 3539:                sum        peak          radius
No lamb, no angles:         -1.0     0.02       0.065887
W/ lamb, no angles:         -1.0     0.02       0.065887
No lamb, w/ angles:         -1.0     0.02       0.065905
W/ lamb, w/ angles:         -1.0     0.05       0.065606
check r4 > r1 due to added wavelengths and angles
r1 = 0.065887, r4 = 0.065606, 2*sigma_r = 0.010086

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Test that drawing with method='fft' also works for SiliconSensor.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python27/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rmandelb/git/GalSim/tests/galsim_test_helpers.py", line 542, in f2
    result = f(*args, **kwargs)
  File "/home/rmandelb/git/GalSim/tests/test_sensor.py", line 254, in test_silicon_fft
    np.testing.assert_almost_equal(im2.array, im3.array, decimal=5)
  File "/home/python27/numpy-1.9.2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 474, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/python27/numpy-1.9.2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/home/python27/numpy-1.9.2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 5 decimals

(mismatch 5.078125%)
 x: array([[  0.00000e+00,   0.00000e+00,  -1.56444e-12, ...,  -1.56294e-12,
          0.00000e+00,   1.74470e-12],
       [  0.00000e+00,   0.00000e+00,  -1.02404e-12, ...,  -1.02327e-12,...
 y: array([[  2.16822e-12,   7.41491e-13,  -2.07719e-12, ...,  -2.08257e-12,
          7.34145e-13,   2.16336e-12],
       [  7.32896e-13,   2.48816e-13,  -7.06088e-13, ...,  -7.06724e-13,...
-------------------- >> begin captured stdout << ---------------------
New, saved array sizes:  (64, 64) (64, 64)
Sum of values:  -0.00481211291247 -0.00480731214711
Minimum image value:  -8.31406699398e-05 -8.31406699398e-05
Maximum image value:  8.22901540185e-05 8.22901540185e-05
Peak location:  2089 2089
Moments Mx, My, Mxx, Myy, Mxy for new array: 
      32.046125        32.473387        90.746406        169.22544        0.039839018    
Moments Mx, My, Mxx, Myy, Mxy for saved array: 
      32.042979        32.5             90.690357        168.54538        4.9714834e-09  
Flux = 3539:  sum        peak         radius
im1:         -0.0     0.00       0.003896
im2:         -0.0     0.00       0.003890
im3:         3539.0     412.35       0.312254

--------------------- >> end captured stdout << ----------------------

```

**Comment by rmjarvis** [comment]
I went ahead and put that sensor bug fix on master and merged it into this branch, so those errors should be gone now.;

**Comment by rmandelb** [comment]
Indeed they are.

**Comment by rmjarvis** [comment]
I think this is ok to merge with 1 review, but I'll give some more time in case anyone else wants to take a look at it.  Plan to merge Wednesday evening.

**Pull request merged**
