### PR TITLE
#661 - WFIRST module accuracy parameters

### PR DESCRIPTION
**Pull request by rmandelb**
This is a short pull request that includes an option to have a higher-fidelity representation of the WFIRST PSFs in Fourier space compared to what you get with the default settings.  See the plots on the issue page for details of how this setting changes the MTF.

I did not put this into the CHANGELOG because this PR will go into the same release as the initial PR for the WFIRST module, so it's basically a slight improvement of one of the new features in this version of GalSim rather than an improvement on a previous version of GalSim.

There is a debatable philosophical point here related to how the WFIRST module is set up:
Unlike OpticalPSF or ChromaticOpticalPSF, the user cannot adjust all the parameters related to the WFIRST optical PSF freely.  Instead, the WFIRST module getPSF() method just has default settings and the new 'high accuracy' settings.  The reason for this choice was that once we are working from the WFIRST pupil plane image, the OpticalPSF kwargs cannot be adjusted freely (i.e., many possible changes to the oversampling or pad factor would result in the routine throwing an exception because the supplied pupil plane image is inadequate in some way).  I think it would take a lot of work to make it possible to adjust the OpticalPSF kwargs completely freely, and I did not feel that it was necessary to do this for an initial version of the WFIRST module.  However, I wanted to flag this design decision, particularly now that we have a 'high accuracy' setting that also isn't adjustable (i.e., it's just a binary choice for default or high accuracy with nothing in between).  Any comments or concerns about this choice?

### CODE REVIEW

**Comment by rmjarvis** [comment]
This looks fine to me.

**Comment by rmandelb** [comment]
Anyone else?  @jmeyers314 ?  @arunkannawadi ?

**Comment by jmeyers314** [comment]
Hey @rmandelb , I thought maybe @barnabytprowe was planning to look at this, but all looks good to me.

**Comment by barnabytprowe** [comment]
Hey guys, sorry for the long non-response on this one... I have been playing a little in spare moments on vacation, quick update.

## Pupil plane image results
Wow, I had no idea this would use so much RAM in high accuracy mode!  Basically way more than my laptop has, and it never completed in reasonable time (e.g. overnight, even.)  Sorry to not be much use here!

## Approximate struts results
I could get the `approximate_struts` image to be better quality and sub 1.e-4 in terms of higher frequency (i.e. ultra-bandpass) gunk without unreasonable memory costs, simply by upping the `oversampling` to 3.5 from 3.0 when building the `OpticalPSF` within `wfirst_psfs.py` (around line 138):
fig2_6_after

The `pad_factor` keyword here has little effect on the amplitude of the bumps, so so much for that idea.  So in terms of this PR I think that I'm happy as is, but might suggest bumping the 3.0 up to 3.5 for `oversampling`.

What I did notice and which I found interesting was that increasing the oversampling helps smooth those bumps, but it does not impact the "continuum" i.e. "green cross" pattern stuff.  Here is an example with oversampling set to 5:
fig2_6_after_os5

Note there is also a slight tail, at the edge of the sharp drop in the MTF at the bandlimit, that is also not reduced by increasing the oversampling.  I don't know the source of this artifact for certain, but my hypothesis is that it is caused by the representation of the curved edges of the pupil using a grid with straight, and sharp, vertical and horizontal boundaries. The reason (I'm guessing) this doesn't "go away" if you increase oversampling or the `pad_factor` is that you aren't in fact reducing the amount of vertical or horizontal edge in the image, you are just switching from vertical to horizontal more often.

I don't know if this is right, and I certainly shouldn't hold up this PR more while I try out the `float` pupil plane idea to try and see if this reduces the effect.  (I'm betting it will.)  I might make an issue for this if there is interest.

Moreover, this idea doesn't really help with the pupil plane image version of the WFIRST PSF.  Does anyone know if there is a vector-graphical representation of the same pupil plane image, in some decipherable polygonal format? (I'm guessing the raster image used here must have come ultimately from some sort of CAD model...)  Because if so it would be really good to try and use that somehow - either by making a smoothed boundary version of what we already have, or using it directly.  But that's an even bigger project.  Probably best to work out if what we have in this PR is good enough.  My preference for sub 1.e-4 artifacts is definitely conservative.

**Comment by barnabytprowe** [comment]
Pithy summary: OK for this PR but might consider oversampling 3.5 for approx_struts.  Harder for the pupil plane version.  Seem to be hitting a bit of a wall that I'd like to understand better.  Will consider opening an issue out of pure personal intrigue!  For WFIRST purposes thinking about how to test what is "good enough" is probably necessary.

**Comment by rmandelb** [comment]
Hi @barnabytprowe - thanks very much for playing around with this!  Now that I'm back, I took your suggestion of increasing the oversampling to 3.5 for ```approximate_struts```.

If nobody raises any objection, I propose to merge this on the morning of Tuesday July 7 (giving time for people who might be off already for the July 4 weekend to comment once they are back).

To address the more detailed points above:
- I agree that it's likely the horizontal/vertical sharp boundaries that are likely causing some of the low-level issues, and this may be worth exploring further at some point.
- For the pupil plane image, I can inquire what formats are available.
- The definition of "good enough" depends on exactly what you're trying to do.  There are many possible uses of these sims and I suspect that the requirements for some are more stringent than for others...

**Comment by rmandelb** [comment]
On another note: once this PR and the other open PR are merged, shall we tag v1.3 sometime next week?

**Comment by rmjarvis** [comment]
Fine with me.  (On both questions.)

**Comment by arunkannawadi** [comment]
Looks good to me.

As far as we know for now, such high accuracy is certainly needed to give these images as inputs to IMCOM. Do we know of any other case where these highly accurate PSFs are a necessity? Currently, the docstring only says that such high accuracies may not be needed for many applications. It may be worthwhile to add a line in the docstring saying explicitly that ``high_accuracy = True`` is needed if a PSF dither sequence is to be used by IMCOM or something of that sort?

**Comment by rmandelb** [comment]
@arunkannawadi - I think it depends a lot on the application, so it's hard to say anything general.  But I agree that it's worth adding a line about applications that require a strictly band-limited PSF with aliasing below a certain limit (such as IMCOM).  Will do that now, and then merge.

**Comment by rmandelb** [comment]
Okay, this is done: https://github.com/GalSim-developers/GalSim/commit/4c3c0c8ac12ee7165bd28137fb019e17b6ce3934

Further docstring tweaks (if necessary) can be done on master before we tag v1.3.

**Pull request merged**
