### PR TITLE
Add a Travis-CI YAML file for continuous integration

### PR DESCRIPTION
**Pull request by joezuntz**
This PR adds a .travis.yml file, which enables integration with the Travis-CI continuous integration service. It replaces the Jarvis CI system, which has not been working for a while since I've been unable to get galsim properly installed there, among other problems.

An example run on this fork can be seen at:
https://travis-ci.org/joezuntz/GalSim/builds/132622083
there are currently no errors but there are some warnings that it might be worth looking into!

If this PR is okay then there are a few more steps to enabling Travis for main GalSim repository:

 - Sign up at travis-ci.org with the GalSim-developers account and accept the github permissions
 - Go to https://travis-ci.org/profile/Galsim-developers and enable CI for galsim

All the best,
Joe

### CODE REVIEW

**Comment by rmjarvis** [comment]
> It replaces the Jarvis CI system

I claim no credit (or blame) for our previous Jenkins system...  :)

**Comment by joezuntz** [comment]
Freudian slip I guess!

**Comment by rmandelb** [comment]
Sounds great to me.  @rmjarvis , do you have any concerns, or should we merge?  I'm happy to take the additional steps Joe outlined to get it going.

**Comment by rmjarvis** [comment]
Sure.  Sounds fine.  

BTW, those "Exception AttributeError" things are due to a bug in astropy 1.1.2.  

And the warnings are because you aren't actually testing the master branch.  (Which reduces the usefulness of CI a skosh.)  You need a `git checkout` master in there.  Probably right after the `git clone` line.

**Comment by joezuntz** [comment]
The CI should run on every branch that it find the .travis.yml file in, unless configured otherwise - if you expand that section by clicking "git.section" in the rounded box to the right you'll see a git checkout step (this is automatic; I didn't set it up). I'm installing astropy with pip so I guess as soon as they fix it that should propagate.

I may have found a problem with the dependency caching - I don't quite understand this, and have just pushed a change that I hope will fix it.

**Comment by joezuntz** [comment]
The change seems to have fixed the error I saw so on my end this is ready to merge.

**Comment by rmjarvis** [comment]
> The CI should run on every branch that it find the .travis.yml file in, unless configured otherwise 

I think we only want this for master branch.  Lots of times, development branches will fail tests during development, so we don't want to be getting noise about that.

OTOH, if it's easy enough, we might want to enable it for branches in pull request.  Not sure how hard that would be to set up to have that distinction.  If that's at all hard, I think limiting to master is perfectly fine.

**Comment by joezuntz** [comment]
Okay, cool - I've added a rule to the .travis.yml that only master should be tested.  The documentation isn't entirely clear about how PRs work - I think that any targeting master will be tested but not 100% sure.

**Comment by rmjarvis** [comment]
That would be awesome if it would automatically test any PR targeting master.  But if not, that's fine too.  Thanks for setting this up.

**Comment by rmjarvis** [comment]
I think this is good to merge, right?

**Comment by rmandelb** [comment]
@joezuntz - this is good to merge, right?

**Comment by joezuntz** [comment]
Yep, this should be good to merge.

**Comment by rmandelb** [comment]
Great.  Will merge now, and then do the other steps you described to enable the CI.

**Comment by joezuntz** [comment]
Great. It won't (I think) start testing until the *next* commit to master is pushed.

**Comment by rmandelb** [comment]
Actually the bigger problem is that when I go there and log in with my github account, it only gives me an option to enable Travis CI for my personal repositories, not the ones belonging to organizations (even those for which I'm an owner, like GalSim-developers).  I did go into the settings for GalSim and enabled Travis CI there (so it would have proper permissions to access the repo).  There's a thread here: https://github.com/travis-ci/travis-ci/issues/2519 that suggests this problem is kind of common and could simply go away after enough tries, or I might need to ping the help desk.  Or maybe someone else has a better idea...

**Comment by rmandelb** [comment]
And sure enough, after my 17th time refreshing the page, GalSim magically appeared as an option.  Awesome.  I've enabled it, and will make a simple test commit to master to get it to run.

**Comment by rmandelb** [comment]
Look here: https://travis-ci.org/GalSim-developers/GalSim/builds (no results yet, but at least it recognizes the fact that there was a commit that should trigger the system and start a build)

**Comment by joezuntz** [comment]
Looks like it has started the build now. The first one will take longer as it doesn't have the dependencies cached.  I think it took 15 minutes the first tome.

**Comment by rmandelb** [comment]
Hmmmm, that didn't work: https://travis-ci.org/GalSim-developers/GalSim/builds/138083930
I have to run to something else really soon, no time to investigate now.

BTW I have noted the use of Travis CI on the GalSim wiki pages (checklist for making a PR and a tagged release) as a reminder to us developers that we should check it out.

**Comment by rmandelb** [comment]
Rather bizarrely, Travis CI counted that as a success (?) and sent me a happy e-mail about it.

**Comment by joezuntz** [comment]
It looks like that's because the "scons tests" command doesn't propagate the return code from the "nosetests" command up to output of scons.  Is that the desired behaviour?

**Comment by joezuntz** [comment]
Could always replace the "scons tests" command with just the plain "nosetests" directly, if the latter runs all the desired tests?

**Comment by jmeyers314** [comment]
>Hmmmm, that didn't work: https://travis-ci.org/GalSim-developers/GalSim/builds/138083930

FWIW, I've just started playing with GalSim on OS X 10.11.5 this evening and I'm now getting the same error.

**Comment by rmjarvis** [comment]
There is a different error listed for my recent PR.  Not sure what that means: 
```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

**Comment by joezuntz** [comment]
Hi Mike - I can see this one:
https://travis-ci.org/GalSim-developers/GalSim/builds/138336687

which has a different error, to do with the module future not being found. Is there another one somewhere?

**Comment by rmjarvis** [comment]
https://travis-ci.org/GalSim-developers/GalSim/builds/138266533

**Comment by joezuntz** [comment]
Ah right - the first line there is:
Could not find .travis.yml, using standard configuration.

So it's assuming you're a ruby programmer (sitting in a cafe in Silicon Valley, with a hipster beard, making a website that will change the world).  Once PRs have the .travis.yml file merged into them that should stop.

**Comment by rmjarvis** [comment]
I see.  That makes sense.  I just merged in from master, so it looks like it's doing a real test now.

Also, I now have `scons tests` exit with an error code if the tests fail, so `scons tests` should be the correct travis integration command.

**Comment by rmjarvis** [comment]
> FWIW, I've just started playing with GalSim on OS X 10.11.5 this evening and I'm now getting the same error.

It was a missing 23.5 in "real_galaxy_catalog_example.fits" that got missed.  Tests are passing now.

**Comment by rmandelb** [comment]
I'm thoroughly confused.  I just got an e-mail that is related to failure due to a commit that I supposedly made, but I didn't make any commits just now: https://travis-ci.org/GalSim-developers/GalSim/builds/138495694 - so I don't see how I could have triggered a build?

**Comment by rmjarvis** [comment]
I just deleted that branch, since it's been merged into master already.  Maybe that triggered it?  And since it doesn't have a .travis.yml file (and we're not hipster Silicon Valley ruby programmers), it failed.

In any case, you can safely ignore it.

**Comment by rmandelb** [comment]
> Maybe that triggered it?

Huh.  If the timing is right, that is probably it.  But I have a hard time imagining any reason to make the deletion of a branch trigger an attempt at building the branch (what is the motivation for that?).  Anyway, thanks for clarifying.  After I got the e-mail I went to look and said "that branch doesn't even EXIST any more?  What is going on??"

> and we're not hipster Silicon Valley ruby programmers

Speak for yourself.  For all you know, I could have an alter ego...  ;)

**Comment by cwwalter** [comment]
> 
> and we're not hipster Silicon Valley ruby programmers
> 
> Speak for yourself. For all you know, I could have an alter ego... ;)

It’s true; I’ve seen her ride her fixed gear bike to get her hand crafted coffee while firing up her engraved macbook to work on her ruby-on-rails application.

It’s hard to keep up!

**Comment by rmjarvis** [comment]
I thought that was you, Chris...  :)

**Pull request merged**
