### PR TITLE
#732- quick correlated noise fix

### PR DESCRIPTION
**Pull request by rmandelb**
This is a one-line fix for the bug noted in #732.  (I also mentioned it in CHANGELOG because in v1.3 it looks like the same error would have occurred.)  

Should I add any unit tests, or is this all good?

### CODE REVIEW

**Comment by rmjarvis** [comment]
This is fine.  I noticed that the `file_name` is listed as a required parameter here, but it's not actually required anymore (now that we have it in the share directory), so I put it in the `opt` list rather than `req`.

If you feel up to it, it would probably be worth having a quick unit test for this, since it's not in any demo script anymore (which serves as unit tests for most of the config stuff).

**Comment by rmandelb** [comment]
Yeah, I agree; was just being lazy.  I tried to make one in https://github.com/GalSim-developers/GalSim/pull/733/commits/696e7075b6448205a9f586acb9bdb191d1c6b394 but I'm getting a somewhat obscure error that I don't understand (in the config innards).  Can you take a look?  If you can get it to run past the point where it currently breaks, then I can sort out any bugs that come in later on that make it not work...

**Comment by rmjarvis** [comment]
Fixed.

**Comment by rmandelb** [comment]
Awesome, thanks.  And the new test passes now, but there's an error when running it on the old version of the code, so that's good.

Do you have any objections to my merging this without another review, given that it's relatively minor?
Should we cherry-pick this onto releases/v1.3 given that it's a bug fix for a problem that was present already in that release?

**Comment by rmjarvis** [comment]
I'm happy to merge now.

And if you want, I can cherry pick this onto the 1.3 branch.  I'm making a 1.3.2 for Scott anyway, since he wants the El Capitan fixes on an official release to use for LSST.  Easy enough to include this too if you want.

**Comment by rmandelb** [comment]
Okay.  I'm merging now.  Please do go ahead and cherry pick onto 1.3, once you're making a 1.3.2 anyway.  Thanks!

**Pull request merged**
