### PR TITLE
Pass DYLD_FALLBACK_LIBRARY_PATH to scons

### PR DESCRIPTION
**Pull request by mjuric**
This makes it easier to build GalSim against buggy Python builds (such as the one shipping with Anaconda; see https://github.com/ContinuumIO/anaconda-issues/issues/498).

Note: in most cases one can get away with adding the path to libpython*.dyld onto `DYLD_LIBRARY_PATH`, but having it on `DYLD_FALLBACK_LIBRARY_PATH` ensures nothing else gets picked up from it that would otherwise get picked up from system paths. E.g., Anaconda also ships with `libz`, but one probably wants to build against the system version, not the Anaconda one.

Related issues: https://jira.lsstcorp.org/browse/SIM-1895, https://github.com/lsst/galsim/pull/9

### CODE REVIEW

**Comment by rmjarvis** [comment]
All looks fine to me.  Thanks, Mario.  I wasn't aware of this FALLBACK set of environment variables.  I certainly don't have a problem with treating this one the same way as the others we do this for.

Do you need me to cherry-pick this over to the 1.3 branch (and make a new revision there)?  Or is this ok just being included in version 1.4 (probably <~ 1 month away)?

**Comment by mjuric** [comment]
Hi @rmjarvis -- merging to master only is fine, thanks!

**Comment by rmandelb** [comment]
Sounds good to me.

**Comment by cwwalter** [comment]
Hi All,

Do we need have both  this and the DYLD_LIBRARY_PATH option which we added at SLAC?

**Comment by rmjarvis** [comment]
I think most of the time, DYLD_LIBRARY_PATH is sufficient.  But Mario wanted the ability to put things in the DYLD_FALLBACK_LIBRARY_PATH as well.  I guess it can make it easier to build in some cases.

**Pull request merged**
