### PR TITLE
Enable Apple clang openmp support

### PR DESCRIPTION
**Pull request by jmeyers314**
Current master doesn't automatically compile for me using Apple clang (Apple LLVM version 10.0.1 (clang-1001.0.46.4)) and `python setup.py build`.  Altering setup.py to add `-Xpreprocessor` in front of `-fopenmp` seems to do the trick.  I don't know, however, if this breaks things for non-Apple clangs.

### CODE REVIEW

**Comment by jmeyers314** [comment]
Okay, I think this is only a partial solution actually.  I can compile and run all the unit tests with this, but if I just do `import galsim` from the python terminal, I get 

```
[meyers18@Temeria ~/src/GalSim (apple_clang_openmp|✔)]$ python
Python 3.7.2 (default, Dec 29 2018, 00:00:04) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import galsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/meyers18/src/GalSim/galsim/__init__.py", line 96, in <module>
    from .position import Position, PositionI, PositionD
  File "/Users/meyers18/src/GalSim/galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: dlopen(/Users/meyers18/src/GalSim/galsim/_galsim.cpython-37m-darwin.so, 2): Symbol not found: ___kmpc_for_static_fini
  Referenced from: /Users/meyers18/src/GalSim/galsim/_galsim.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/meyers18/src/GalSim/galsim/_galsim.cpython-37m-darwin.so
```

which is some kind of openmp library not being loaded error.
If I `import numpy` first though, then I don't get an error, which is apparently what allows the unit tests to complete.  So I guess numpy somehow loads the openmp library into a place that the galsim .so can find it?

**Comment by rmjarvis** [comment]
I knew we'd need to adjust the openmp stuff, since the icpc flag isn't right.  I just thought it would be easier to merge James's PR and then work on this separately.  Sorry this broke installation for you.

I was planning to copy over the way TreeCorr checks for openmp.  It has some nominal flags to try, but it also tries them out to see if they work before committing to them.  Can you let me know whether you can successfully install TreeCorr from source on your machine?  Also whether it ends up keeping the openmp flag or not?  (It might just fail and fall back to the non-openmp clang installation.)

If that doesn't get openmp for you, then we can experiment with adding additional options to try that might work on Apple clang.  My Apple clang doesn't have openmp support, so I haven't been able to test it much.

**Comment by jmeyers314** [comment]
TreeCorr `python setup.py build` yields:

```
...
Compiler is Clang.  Checking if it is a version that supports OpenMP.
Trying compile command:
gcc -fopenmp -O3 -ffast-math -c /Users/meyers18/src/TreeCorr/tmp/tmpzpdj2jls.cpp -o /Users/meyers18/src/TreeCorr/tmp/tmpmopp8w5q.os
Output was:
    clang: error: unsupported option '-fopenmp'


Sorry.  This version of clang doesn't seem to support OpenMP.
```

This is on a different computer with Apple LLVM version 9.0.0 (clang-900.0.39.2), but that version has the same problem on GalSim, so I think this is the same issue.

> My Apple clang doesn't have openmp support, so I haven't been able to test it much.

Are you sure?  I think there has been some support for openmp for a while (if the library is installed separately), just not directly built into the compiler: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

**Comment by rmjarvis** [comment]
Try the current version.  I kept your -Xpreprocessor thing as an additional option that TreeCorr doesn't try.  It seems to work for me.  The thing that is needed though is the link flag -- `-fopenmp` needs to be there too.

**Comment by rmjarvis** [comment]
Still doesn't work on my machine actually.  It compiles, but doesn't have the right library to link to.  But if you've gotten other clang things to compile with OpenMP then maybe it will work for you.  Or maybe you can figure out what link flag might be required (in addition to or instead of `-fopenmp`).

**Comment by rmjarvis** [comment]
OK.  Try now.  I think it's working.  I just needed to make sure the link check included the -L flags that include the Anaconda libraries, which is where libgomp.dylib lives for me at least.  Probably requires `conda install llvm-openmp` I suspect.

**Comment by jmeyers314** [comment]
Hmmm... My openmp is via homebrew.  I tried `conda install llvm-openmp` though.  Now I get (whether or not I try the conda openmp):

```
Compiler is Clang.  Checking if it is a version that supports OpenMP.
cmd =  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/include -arch x86_64 -I/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/include -arch x86_64 -O2 -msse2 -std=c++11 -fopenmp -Wno-shorten-64-to-32 -fvisibility=hidden -stdlib=libc++ -g -c /Users/meyers18/src/GalSim/tmp/tmpzi2ptefy.cpp -o /Users/meyers18/src/GalSim/tmp/tmpmk0fh007.os
Trying compile command:
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/include -arch x86_64 -I/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/include -arch x86_64 -O2 -msse2 -std=c++11 -fopenmp -Wno-shorten-64-to-32 -fvisibility=hidden -stdlib=libc++ -g -c /Users/meyers18/src/GalSim/tmp/tmpzi2ptefy.cpp -o /Users/meyers18/src/GalSim/tmp/tmpmk0fh007.os
Output was:
    clang: error: unsupported option '-fopenmp'

cmd =  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/include -arch x86_64 -I/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/include -arch x86_64 -O2 -msse2 -std=c++11 -Xpreprocessor -fopenmp -Wno-shorten-64-to-32 -fvisibility=hidden -stdlib=libc++ -g -c /Users/meyers18/src/GalSim/tmp/tmpiqxmr8gt.cpp -o /Users/meyers18/src/GalSim/tmp/tmp9s547s5p.os
cmd =  gcc -bundle -undefined dynamic_lookup -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -fopenmp /Users/meyers18/src/GalSim/tmp/tmp9s547s5p.os -o /Users/meyers18/src/GalSim/tmp/tmpwzl2sb7p.exe
Trying link command:
gcc -bundle -undefined dynamic_lookup -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -fopenmp /Users/meyers18/src/GalSim/tmp/tmp9s547s5p.os -o /Users/meyers18/src/GalSim/tmp/tmpwzl2sb7p.exe
Output was:
    clang: error: unsupported option '-fopenmp'

cmd =  g++ -bundle -undefined dynamic_lookup -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -fopenmp /Users/meyers18/src/GalSim/tmp/tmp9s547s5p.os -o /Users/meyers18/src/GalSim/tmp/tmpwzl2sb7p.exe
Trying link command:
g++ -bundle -undefined dynamic_lookup -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -fopenmp /Users/meyers18/src/GalSim/tmp/tmp9s547s5p.os -o /Users/meyers18/src/GalSim/tmp/tmpwzl2sb7p.exe
Output was:
    clang: error: unsupported option '-fopenmp'


Sorry.  This version of clang doesn't seem to support OpenMP.

If you think it should, you can use `python setup.py build --debug`
to get more information about the commands that failed.
You might need to add something to your C_INCLUDE_PATH or LIBRARY_PATH
(and probabaly LD_LIBRARY_PATH) to get it to work.
```

If I change `lopt['clang w/ manual OpenMP'] = ['-lomp']` then it compiles (it passes the link test), though the link command at the end doesn't appear to actually respect the `lopt` commands.  I.e., it executes:
`g++ -bundle -undefined dynamic_lookup -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -L/Users/meyers18/src/lsst/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/pysrc/SBDeconvolve.o build/temp.macosx-10.7-x86_64-3.7/pysrc/WCS.o build/temp.macosx-10.7-x86_64-3.7/pysrc/RealGalaxy.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Horner.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Image.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBBox.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Bessel.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Table.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBProfile.o build/temp.macosx-10.7-x86_64-3.7/pysrc/module.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Silicon.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBSersic.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Random.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBVonKarman.o build/temp.macosx-10.7-x86_64-3.7/pysrc/HSM.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBShapelet.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Interpolant.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBMoffat.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBInclinedExponential.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBConvolve.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBAiry.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBInterpolatedImage.o build/temp.macosx-10.7-x86_64-3.7/pysrc/CDModel.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBSpergel.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBKolmogorov.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Integ.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBExponential.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBAdd.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBDeltaFunction.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBGaussian.o build/temp.macosx-10.7-x86_64-3.7/pysrc/PhotonArray.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBInclinedSersic.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBTransform.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBSecondKick.o build/temp.macosx-10.7-x86_64-3.7/pysrc/SBFourierSqrt.o build/temp.macosx-10.7-x86_64-3.7/pysrc/Bounds.o -L/Users/meyers18/src/lsst/stack/miniconda3-4.5.12-1172c30/DarwinX86/fftw/3.3.4.lsst2/lib -Lbuild/temp.macosx-10.7-x86_64-3.7 -lgalsim -lfftw3 -lgalsim -o build/lib.macosx-10.7-x86_64-3.7/galsim/_galsim.cpython-37m-darwin.so -Xpreprocessor -fopenmp -stdlib=libc++`

**Comment by rmjarvis** [comment]
You're right.  I wasn't using the lflags later where we actually build the library.  I think I fixed that.
Also, what is your clang version.  I'm on High Sierra, and I get
```
$ which gcc
/usr/bin/gcc
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
$ gcc -c -fopenmp src/Silicon.cpp -Iinclude -Iinclude/galsim
$
```
I was surprised that you were getting different behavior with respect to the `-fopenmp` directive.

**Comment by jmeyers314** [comment]
That's interesting, I'm on Mojave and get:
```
(lsst-scipipe-1172c30) [meyers18@gamma ~/src/GalSim (apple_clang_openmp|✚1)]$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(lsst-scipipe-1172c30) [meyers18@gamma ~/src/GalSim (apple_clang_openmp|✚1)]$ gcc -c -fopenmp src/Silicon.cpp -Iinclude -Iinclude/galsim
clang: error: unsupported option '-fopenmp'
```

I think I got everything to work on my computer now.  Part of my problem seems to be that I had anaconda packages (numpy, scipy, etc...) that were linked against the intel-openmp runtime library (I think via mkl; this is from the LSST stack binary installation), but I was trying to link galsim against either homebrew's openmp or the conda llvm-openmp library, which are apparently incompatible.  If I direct galsim to also link against intel, then everything seems to work.  To be doubly confusing though, the intel library doesn't come with omp.h, so I had to compile against homebrew, but link against intel, which feels a little weird.  The first reply [here](https://software.intel.com/en-us/forums/intel-c-compiler/topic/611485) suggests that maybe using a different source for the .h is standard though?

The safest way to handle this seemed to be adding yet another clang variant to the `copts` and `lopts` list.

The final weird thing is that, while all the tests pass, the last lines of output from running `python setup.py test` now are:
```
...
-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================================================ 594 passed, 1 skipped, 15 warnings in 158.98 seconds ============================================================================================
All python tests passed.
compiler version information: 
ccache version 3.6

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2019 Joel Rosdahl

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
Unknown compiler.
Check if the compiler works like  gcc
Check if the compiler works like  clang w/ OpenMP
Check if the compiler works like  clang w/ manual OpenMP
Check if the compiler works like  clang w/ Intel OpenMP
Using compiler ccache, which is clang w/ Intel OpenMP
Using ccache
The compiler ccache with flags -O2 -msse2 -std=c++11 -Xpreprocessor -fopenmp -Wno-shorten-64-to-32 -fvisibility=hidden did not successfully compile C++11 code
error: Compiler is not C++-11 compatible
```

Which I guess means the c++ tests didn't build?

**Comment by rmjarvis** [comment]
Hm.  Not sure why try_cpp11 would fail when doing the tests, but not when building the library.  Probably need to add some print statements to debug that.  Maybe some logic is wrong there.

(There is at least some logging error related to ccache there, but I don't **think** that should be substantive to the build tests.)

**Comment by jmeyers314** [comment]
Your latest changes almost work for me now; thanks.  Switching the link flag from `-fopenmp` to `-lomp` means my computer now settles on `clang w/ manual openmp` instead of `clang w/ Intel openmp`.  This does compile and link, but fails during the tests with the message:

```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

which is the intel-openmp vs home-brew openmp incompatibility.

If `setup.py` searches for the intel variant first though, then everything compiles, links, and the python tests run fine.

The last thing is that when linking the cpp-tests the conda library path that includes the intel-openmp lib is not included.  So either I need to add the conda path to my `LIBRARY_PATH` var, or setup.py could detect and append $CONDA_PREFIX.  I.e., the following test command *does* work for the cpp tests: 

`LIBRARY_PATH=$CONDA_PREFIX/lib python setup.py test`

**Comment by rmjarvis** [comment]
That was what this bit was supposed to do:

**Comment by rmjarvis** [comment]
On my machine I also needed the conda lib directory in DYLD_LIBRARY_PATH to find it at run time.  I thought the linker_so should already explicitly add it as a -L flag for linking.  Is it not there for you?  Maybe we can explicitly add the CONDA_PREFIX/lib as well (and to LIBRARY_PATH) if CONDA_PREFIX is in the environment.

**Comment by jmeyers314** [comment]
Yep, this appears to work for me with both apple clang 9.0 and 10.0.  If travis passes, then I'll plan to merge this afternoon.

**Pull request merged**
