### PR TITLE
Try out GHA with python 3.11

### PR DESCRIPTION
**Pull request by jmeyers314**

### CODE REVIEW

**Comment by rmjarvis** [comment]
```
tests/run_examples.py::test_psf_wf_movie
tests/run_examples.py::test_psf_wf_movie
  /home/runner/work/GalSim/GalSim/examples/psf_wf_movie.py:34: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(matplotlib.__version__) < LooseVersion('1.2'):

tests/run_examples.py::test_fft_vs_geom_movie
tests/run_examples.py::test_fft_vs_geom_movie
  /home/runner/work/GalSim/GalSim/examples/fft_vs_geom_movie.py:54: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(matplotlib.__version__) < LooseVersion('1.2'):
```
No errors. These are the only warnings.  I think we can probably just remove these checks entirely.  matplotlib v1.2 is really quite old at this point.  Probably fine to let the user get an error if they still have it.

**Comment by jmeyers314** [comment]
I'm wondering if something is wrong with the pip caching.  For the Linux builds, it's 10-30 MB.  For the Macos build, it's about 2.2 GB and consequently rather slow to download.  Should we kick it maybe?

**Comment by jmeyers314** [comment]
Okay, macos cache is still coming in at 2.2GB.  I'll leave it to you, @rmjarvis , if you want to continue to investigate, but I think I'm happy enough now with this.

**Comment by rmjarvis** [comment]
I fought a while with the caches on Travis back when we used that.  GHA seems better, but I don't really have any insights as to why mac would be so different from the linux ones.  Probably just leave it for now.

**Review by rmjarvis — APPROVED** [review]

**Pull request merged**
