### PR TITLE
#712 Fix error in CCDNoise getVariance function

### PR DESCRIPTION
**Pull request by rmjarvis**
@dkirkby pointed out an error in the CCDNoise getVariance function.  The correct formula is:
```
var = sky_level/gain + (read_noise/gain)**2
```
This PR fixes this error.  It also adds some unit tests that check that when CCDNoise adds noise to an image, this is actually the variance of the resulting noise field.

For completeness, I also added the same check for Gaussian and Poisson noise, which both passed.

### CODE REVIEW

**Comment by rmandelb** [comment]
Looks good to me.

**Comment by rmandelb** [comment]
... except I just noticed that I have a test failure (CCDNoise variance).  Is it not deterministic?

**Comment by rmjarvis** [comment]
I think it is deterministic.  Which test is failing for you?  Maybe you didn't recompile?  The change is in the C++ layer, so perhaps scons caching is messing something up and it didn't compile the new code.

**Comment by rmandelb** [comment]
Looking back through the terminal history, I confirm that i ran scons and scons install before running the test suite.  And it appears to have recognized it had to recompile pysrc/Noise.cpp.

I just re-scons'ed and ran the tests again - same exact failure with same exact numbers, so yep, deterministic.  :)

Then I used scons -c to clean up, re-compiled everything, and still I get the exact same failure:
```
======================================================================
FAIL: Test CCD Noise generator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rmandelb/git/GalSim/tests/test_random.py", line 1449, in test_ccdnoise
    err_msg='Realized variance for CCDNoise did not match getVariance()')
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/numpy/testing/utils.py", line 468, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 1 decimals
Realized variance for CCDNoise did not match getVariance()
 ACTUAL: 19.333929061889648
 DESIRED: 19.444444444444446
-------------------- >> begin captured stdout << ---------------------
variance =  19.3339290619
getVar =  19.4444444444

--------------------- >> end captured stdout << ----------------------
```

Am I missing something?

**Comment by rmandelb** [comment]
I should add: this is on my mac.  On the linux cluster here, it all worked fine when I did scons / scons install / scons tests, no need to do any cleanup.

**Comment by rmjarvis** [comment]
OK, it doesn't seem to be a cleanup issue then.  If you still had the old code, it would be very different from that.  On my machine the measured value 19.42, so I'm not sure why you get a different value here.

Update: I found a machine that gets the same answer you do.  (A linux box, in my case.)  So I can at least investigate and try to see why they get different answers.

**Comment by rmandelb** [comment]
In case it�s relevant, I have numpy 1.6.1.

**Comment by rmjarvis** [comment]
Yep.  I think that's it.  The one that fails for me is numpy 1.7.0.  The others are newer.  I think numpy changed their definition of var at some point.  The noise arrays in the two cases seem to be identical.  But the variance that numpy returns is different.  I'll see if I can figure out what the right function is to compute the variance we want here.  (Might be related to mean subtraction I'm guessing.  Still looking into it though...)

**Comment by rmjarvis** [comment]
I figured it out.  Older versions of numpy don't use double precision in calculating statistics of single precision arrays.  Apparently with 4 million values, the errors added up enough to give the wrong answer for the variance.  Switching to dtype=float fixed it.

**Comment by rmandelb** [comment]
Yep, that works, thanks!

**Comment by rmjarvis** [comment]
Since @dkirkby pointed out even more errors in the docs related to CCDNoise as well as inconsistencies with the units in demo3, I went through everything associated with CCDNoise, and I think the docs are all correct now.  I also discovered some similar errors in the config-layer CCDNoise handling, but in code paths that we don't use anywhere.  To remedy that, I added unit tests to check those code paths.

I think things are all consistent now.  So David, please take a look and see if you think I covered everything.  And thanks very much for catching these errors!

**Comment by dkirkby** [comment]
I didn't try running the new code but, reading it through, I didn't spot any lingering problems.  Thanks!

(For future consideration: these types of problems could be mitigated by attaching units to constants like read noise and gain.  See [here](https://github.com/desihub/specsim/blob/228e503b44960412db81fea26955ddca2d5641b6/specsim/data/config/desi.yaml#L80) for example.)

**Pull request merged**
